codecov:
  branch: main
  strict_yaml_branch: main
coverage:
  range: 70..85
  round: down
  precision: 0
comment:
  layout: " diff, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false